export const GET_PHOTO = 'GET_PHOTO'
export const UPDATE_SEARCH_QUERY_LIST = 'UPDATE_SEARCH_QUERY_LIST'
export const DELETE_SEARCH_QUERY = 'DELETE_SEARCH_QUERY'
export const HANDLE_ERRORS = 'HANDLE_ERRORS'
